In [2]:
import numpy as np

In [13]:
myList = [1,2,3]

In [14]:
type(myList)

list

In [15]:
np.array(myList)

array([1, 2, 3])

In [17]:
myarray = np.array(myList)

In [18]:
myarray

array([1, 2, 3])

In [19]:
type(myarray)

numpy.ndarray

In [23]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [28]:
np.zeros(shape=(10, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [30]:
np.ones(shape=(2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.random.seed(101)
arr = np.random.randint(0,100, 10)


In [34]:
arr

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [36]:
arr2 = np.random.randint(0,100,10)

In [37]:
arr2

array([49, 83,  8, 29, 59, 34, 44, 72, 19, 10])

In [38]:
arr.max()

95

In [39]:
arr.argmax()

0

In [41]:
arr.min()

9

In [42]:
arr.argmin()

7

In [43]:
arr.mean()

60.8

In [45]:
arr.reshape((2, 5))

array([[95, 11, 81, 70, 63],
       [87, 75,  9, 77, 40]])

In [56]:
mat = np.arange(0, 100).reshape(10,10)

In [57]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [59]:
row = 6
col = 4

In [60]:
mat[row, col]

64

In [61]:
mat[:,1]

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [62]:
mat[:,1].reshape(10, 1)

array([[ 1],
       [11],
       [21],
       [31],
       [41],
       [51],
       [61],
       [71],
       [81],
       [91]])

In [63]:
mat[2, :]

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [69]:
mat[0:3,0:3]

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [70]:
mat[0:3,0:4] = 0

In [71]:
mat

array([[ 0,  0,  0,  0,  4,  5,  6,  7,  8,  9],
       [ 0,  0,  0,  0, 14, 15, 16, 17, 18, 19],
       [ 0,  0,  0,  0, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])